### ISSUE TITLE
ClassNotFoundException: com.yandex.mobile.ads.unity.wrapper.banner.UnityBannerListener

### ISSUE THREAD

**Issue by crokocat** [yandexmobile/yandex-ads-unity-plugin#23]
При запуске на устройстве:
2022-07-11 17:20:32.947 31446-31493/in.x42.zenbox E/Unity: AndroidJavaException: java.lang.ClassNotFoundException: com.yandex.mobile.ads.unity.wrapper.banner.UnityBannerListener
    java.lang.ClassNotFoundException: com.yandex.mobile.ads.unity.wrapper.banner.UnityBannerListener
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:216)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)

Unity 2021.1.12

Установлен плагин яндекс-рекламы версии 2.1.1.

Android Resolver настроен, стоит Auto-resolve, Enable Auto Resolution, Enable Resolution on Build;

В proguard-user.txt добавлено исключение: 
-keep class com.yandex.mobile.ads.** { *; }

**Comment by mobile-ads-github** [comment]
Добрый день, спасибо за обращение, разберемся.

**Comment by mobile-ads-github** [comment]
Здравствуйте

Проверьте, пожалуйста, что при импорте ассета плагина вы добавляете в проект все файлы плагина, в том числе и ```mobileads-unity-plugin-2.2.0.aar```. Проверьте также, что в артефактах, сгенерированных proguard при сборке приложения, есть UnityBannerListener.

UnityBannerListener - это часть ```mobileads-unity-plugin-2.2.0.aar```, он поставляется как часть плагина.
