### ISSUE TITLE
SDK API usage from a background thread detected. Please, use SDK API just from the main thread.

### ISSUE THREAD

**Issue by JasonBrodyHM** [yandexmobile/yandex-ads-unity-plugin#50]
Столкнулся с такой проблемой при которой не работает показ рекламы в после сбора билда. "2023.02.11 22:52:09.770 23649 23688 Error Unity AndroidJavaException: com.yandex.mobile.ads.impl.o40: SDK API usage from a background thread detected. Please, use SDK API just from the main thread."

**Comment by dreamcodestudio** [comment]
Аналогичная ситуация на Yandex Mobile Ads v5.5.0
```
AndroidJavaException: com.yandex.mobile.ads.impl.o40: SDK API usage from a background thread detected. Please, use SDK API just from the main thread.
 com.yandex.mobile.ads.impl.o40: SDK API usage from a background thread detected. Please, use SDK API just from the main thread.
at com.yandex.mobile.ads.impl.h70.a(SourceFile:3)
at com.yandex.mobile.ads.unity.wrapper.rewarded.a.a(Unknown Source:2)
at com.yandex.mobile.ads.unity.wrapper.rewarded.RewardedAdWrapper.<init>(Unknown Source:10)
at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
at UnityEngine.AndroidJNISafe.CheckException () [0x00
```

**Comment by mobile-ads-github** [comment]
Здравствуйте, мы исправим проблему в ближайшем релизе плагина. Релиз планируем в середине этой недели.
Спасибо за репорт!

**Comment by JasonBrodyHM** [comment]
Здравствуйте, когда ожидать обновление плагина? Неделя как бы уже заканчивается, а релиз обещали в ее середине.

**Comment by dreamcodestudio** [comment]
c версии 2.7.0 не воспроизводится

**Comment by mobile-ads-github** [comment]
Добрый день, выпустили релиз с фиксом 2.7.0
