### ISSUE TITLE
Ошибка android 12 

### ISSUE THREAD

**Issue by sbmgamescom** [yandexmobile/yandex-ads-unity-plugin#9]
Не могу никак исправить. Думаю дело в самой библиотеки. 

2022-03-09 20:29:19.039 8431-8431/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.SbmGames.SchulteTable:Metrica, PID: 8431
    java.lang.RuntimeException: Unable to create service com.yandex.metrica.ConfigurationJobService: java.lang.IllegalArgumentException: com.SbmGames.SchulteTable: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4500)
        at android.app.ActivityThread.access$1700(ActivityThread.java:247)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2072)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.IllegalArgumentException: com.SbmGames.SchulteTable: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at com.yandex.metrica.impl.ob.Re.<init>(SourceFile:4)
        at com.yandex.metrica.ConfigurationJobService.onCreate(SourceFile:7)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4487)
        	... 9 more

**Comment by sbmgamescom** [comment]
![image](https://user-images.githubusercontent.com/46422509/157462098-697ee404-1f6d-442a-b026-6117be24b130.png)

**Comment by mobile-ads-github** [comment]
Добрый день, подскажите пожалуйста, какую версию Unity плагина SDK вы используете. Вероятнее всего обновление до версии 2.0.0 должно решить вашу проблему. Спасибо!
